### ISSUE TITLE
Broken link in tutorial

### ISSUE THREAD

**Issue by zoidbergwill** [Leo-G/Flask-SQLALchemy-RESTFUL-API#2]
Hi.

I wasn't sure to comment on your blog post or submit an issue here. Your blog post's link to this repo is broken:

`<p>The complete code is available at<a href="%20https://github.com/Leo-G/Flask-SQLALchemy-RESTFUL-API" target="_blank"> https://github.com/Leo-G/Flask-SQLALchemy-RESTFUL-API</a></p>`

The space at the beginning of the link makes it think it's a relative URL on your blog.

**Comment by Leo-G** [comment]
Thank you so much, I have fixed the issue
